
# Configuracion del Blog

title: "Mi Blog de Actualidad"
email: "cjhernandez0908@gmail.com"
description: "Un espacio dedicado a los análisis y opiniones sobre los temas más relevantes de la actualidad."
baseurl: "/Indalo-bot.github.io"
url: https://indalo-bot.github.io/
twitter_username: "CarlosH22446637"
github_username:  "Indalo-bot"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-admin
lang: "es-ES"
permalink: /:year/:month/:day/:title/
paginate: 5  # Número de entradas por página
paginate_path: "/page:num"

